services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/backend/
    ports:
      - 8080:8080

  db:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432

volumes:
  postgres_data:
